name: Build ADB GUI Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Download platform-tools
        run: |
          curl -Lo platform-tools.zip https://dl.google.com/android/repository/platform-tools-latest-windows.zip
          powershell -Command "Expand-Archive platform-tools.zip -DestinationPath platform-tools"

      - name: Build exe with logo
        run: |
          pyinstaller --onefile --noconsole adb_gui.py ^
          --icon=logo.ico ^
          --add-data "platform-tools;platform-tools" ^
          --name=ADB_Manager_GUI

      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Create Inno Setup Script
        run: |
          echo [Setup] > installer.iss
          echo AppName=ADB Manager GUI >> installer.iss
          echo AppVersion=1.0 >> installer.iss
          echo DefaultDirName={pf}\\ADB_Manager_GUI >> installer.iss
          echo DefaultGroupName=ADB Manager GUI >> installer.iss
          echo UninstallDisplayIcon={app}\\ADB_Manager_GUI.exe >> installer.iss
          echo OutputDir=dist >> installer.iss
          echo OutputBaseFilename=ADB_Manager_GUI_Installer >> installer.iss
          echo Compression=lzma >> installer.iss
          echo SolidCompression=yes >> installer.iss
          echo [Files] >> installer.iss
          echo Source: "dist\\ADB_Manager_GUI.exe"; DestDir: "{app}"; Flags: ignoreversion >> installer.iss
          echo Source: "platform-tools\\*"; DestDir: "{app}\\platform-tools"; Flags: recursesubdirs ignoreversion >> installer.iss
          echo [Icons] >> installer.iss
          echo Name: "{group}\\ADB Manager GUI"; Filename: "{app}\\ADB_Manager_GUI.exe" >> installer.iss
          echo Name: "{commondesktop}\\ADB Manager GUI"; Filename: "{app}\\ADB_Manager_GUI.exe" >> installer.iss
          echo Name: "{group}\\Uninstall ADB Manager GUI"; Filename: "{uninstallexe}" >> installer.iss

      - name: Build Installer
        run: iscc installer.iss

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: ADB_Manager_GUI_Installer
          path: dist/ADB_Manager_GUI_Installer.exe
          
